//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.AzureModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class shufti_log
    {
        public int id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string status { get; set; }
        public string declined_reason { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string birthday { get; set; }
        public string document_number { get; set; }
        public string expiry_date { get; set; }
        public string issue_date { get; set; }
    }
}
