//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.AzureModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_table()
        {
            this.trans_history = new HashSet<trans_history>();
            this.trans_history1 = new HashSet<trans_history>();
        }
    
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<bool> emailVerified { get; set; }
        public Nullable<System.Guid> emailCode { get; set; }
        public string IBAN { get; set; }
        public string SWIFT { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public Nullable<System.DateTime> signup { get; set; }
        public Nullable<bool> listme { get; set; }
        public string qrkey { get; set; }
        public string phone { get; set; }
        public Nullable<bool> phoneVerified { get; set; }
        public Nullable<bool> kycVerified { get; set; }
        public string birthday { get; set; }
        public string beneficiery { get; set; }
        public string bank { get; set; }
        public Nullable<bool> check_btc { get; set; }
        public Nullable<bool> check_eth { get; set; }
        public Nullable<bool> btc_cash { get; set; }
        public Nullable<bool> eth_cash { get; set; }
        public Nullable<double> btc_cash_com { get; set; }
        public Nullable<double> eth_cash_com { get; set; }
        public Nullable<bool> btc_wire { get; set; }
        public Nullable<bool> eth_wire { get; set; }
        public Nullable<double> btc_wire_com { get; set; }
        public Nullable<double> eth_wire_com { get; set; }
        public Nullable<double> from_cash { get; set; }
        public Nullable<double> to_cash { get; set; }
        public Nullable<bool> qrScanned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trans_history> trans_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trans_history> trans_history1 { get; set; }
    }
}
